// Command keygen 生成 RSA-2048 keypair，输出可直接粘贴到 .env 的格式：
//
//	go run ./cmd/keygen
//	go run ./cmd/keygen -out .env.test   // 直接写到指定文件
//	go run ./cmd/keygen -bits 4096      // 生成 4096-bit key
//
// 输出示例：
//
//	# ===== SECURITY (auto-generated by cmd/keygen on 2026-06-22T10:00:00Z) =====
//	SIGN_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
//	SIGN_PUBLIC_KEY="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8..."
//
// 把这两行粘到 .env / .env.test / .env.production 即可。
package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"time"
)

func main() {
	out := flag.String("out", "", "optional output file (e.g. .env.test); empty = stdout")
	bits := flag.Int("bits", 2048, "RSA modulus bits (2048 / 3072 / 4096)")
	flag.Parse()

	priv, err := rsa.GenerateKey(rand.Reader, *bits)
	if err != nil {
		log.Fatalf("rsa.GenerateKey: %v", err)
	}

	privDER, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		log.Fatalf("MarshalPKCS8PrivateKey: %v", err)
	}
	privPEM := string(pemEncode("PRIVATE KEY", privDER))

	pubDER, err := x509.MarshalPKIXPublicKey(&priv.PublicKey)
	if err != nil {
		log.Fatalf("MarshalPKIXPublicKey: %v", err)
	}
	pubB64 := base64.StdEncoding.EncodeToString(pubDER)

	content := renderEnvBlock(privPEM, pubB64, *bits)

	if *out != "" {
		// 追加模式：避免覆盖已有配置。
		f, err := os.OpenFile(*out, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
		if err != nil {
			log.Fatalf("open %s: %v", *out, err)
		}
		defer f.Close()
		if _, err := f.WriteString("\n" + content); err != nil {
			log.Fatalf("write: %v", err)
		}
		fmt.Fprintf(os.Stderr, "✓ appended RSA-%d keypair to %s\n", *bits, *out)
		return
	}
	fmt.Print(content)
}

// pemEncode 把 DER 字节包装为 PEM block。
func pemEncode(typ string, der []byte) []byte {
	const lineLen = 64
	var out strings.Builder
	out.WriteString("-----BEGIN " + typ + "-----\n")
	b64 := base64.StdEncoding.EncodeToString(der)
	for i := 0; i < len(b64); i += lineLen {
		end := i + lineLen
		if end > len(b64) {
			end = len(b64)
		}
		out.WriteString(b64[i:end])
		out.WriteByte('\n')
	}
	out.WriteString("-----END " + typ + "-----\n")
	return []byte(out.String())
}

// renderEnvBlock 输出 .env 友好的格式块（保留换行为 \n）。
func renderEnvBlock(privPEM, pubB64 string, bits int) string {
	privOneLine := strings.ReplaceAll(strings.TrimSpace(privPEM), "\n", `\n`)
	return fmt.Sprintf(
		"# ===== SECURITY (auto-generated by cmd/keygen on %s, RSA-%d) =====\n"+
			"SIGN_PRIVATE_KEY=\"%s\"\n"+
			"SIGN_PUBLIC_KEY=\"%s\"\n"+
			"SECURITY_ENCRYPT_ENABLED=true\n",
		time.Now().UTC().Format(time.RFC3339), bits, privOneLine, pubB64,
	)
}
